[package]
name = "stream-fusion-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
stream-fusion-core = { path = "../stream-fusion-core" }
stream-fusion-storage = { path = "../stream-fusion-storage" }
stream-fusion-flight = { path = "../stream-fusion-flight" }
tokio.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
